### PR TITLE
Updating node-inspector

### PR DESCRIPTION
**Pull request by badave**
I was having issues installing v8-debug.  Updating node-inspector updates v8-debug to a much more recent version which works.

### CODE REVIEW

**Comment by akamensky** [comment]
Hi @badave Thanks for your contribution! Just one note, I would like to avoid dependencies with "^" as had issue with certain version of portscanner (I think it was just one after 1.0.0, newer may work fine tho). So I chose to pin the exact version number so it can be fully tested.

Would you consider updating your changes and pin them to the versions you tested with?

**Comment by akamensky** [comment]
Also since I setup automatic release you can bump the version to next minor, then it will be automatically updated on npm.

**Comment by scottmas** [comment]
This update is essential for my environment. 

As a consumer of Nodev, my two cents are that I would prefer having "^" dependencies that pull in the latest minor version. And this IS the standard dependency setting for dev tools. For example, I wouldn't even need this patchset if we were already using "^" since I would have installed the latest 0.13.x automatically.

**Comment by akamensky** [comment]
Alright, I will take this feedback then.

**Comment by scottmas** [comment]
Sweet, akamensky & badave. This is a fantastic package.

**Pull request merged**
